### PR TITLE
complete astronaut bg video and slideshow component

### PR DESCRIPTION
**Pull request by Oliverwong123**
Complete astronaut video and slideshow components using bootstrap grid system.
Our app looks nice on mobile devices and tablet devices 😜

test URL:
localhost:4200/astronaut

### CODE REVIEW

**Comment by Oliverwong347** [comment]
So cool! 🐼🤖👽🤟

**Comment by Oliverwong369** [comment]
Good job! Witcher.
SOOO COOOL! We can tag this commit as "v0.0.1". 🤖
Have a good weekend everyone! @Oliverwong123 @Oliverwong347  🏝☀️🕶

**Comment by Oliverwong347** [comment]
Have a good weekend! @Oliverwong369 🐼

**Comment by Oliverwong123** [comment]
Have a nice weekend! @Oliverwong369 👽

**Pull request merged**
